language: d
sudo: required

apt_packages:
  - cmake

install:
  - git clone https://github.com/nanomsg/nanomsg.git
  - pushd nanomsg
  - cmake .
  - make -j`nproc`
  - sudo make install
  - sudo ldconfig
  - popd

script:
  - dub test
  - dub build
  - make -C examples

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.082.1
    - d: dmd-2.081.2
    - d: dmd-2.080.1
    - d: ldc-1.12.0
    - d: ldc-1.11.0
    - d: ldc-1.10.0
  allow_failures:
    - d: dmd-nightly
